name: Deploy Web to Another Repo

on:
  push:
    branches:
      - main # Cambia esto a 'master' si tu rama principal se llama master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Usa la versión estable de Flutter

      - name: Build Web
        run: |
          flutter pub get
          flutter build web --release --base-href "/jocar-web/"

      - name: Deploy to External Repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web # La carpeta que genera Flutter
          # ⚠️ CAMBIA ESTO: Pon tu usuario de GitHub y el nombre del repo destino de la Web
          repository-name: YaelZamora/jocar-web
          branch: gh-pages # O la rama donde almacenes tu web (usualmente main o gh-pages)
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }} # Aquí lee el secreto que guardamos en el Paso 2
